### ISSUE TITLE
Doom CLI Rewrite

### ISSUE THREAD

**Issue by hlissner** [hlissner/doom-emacs#4273]
I've been working on this CLI rewrite for a while. Over time, bug reports have trickled in about various problems that this rewrite directly or indirectly fixes. To reduce the noise I'm consolidating those and futures posts into this one, to represent the rewrite:

## Primary goals of this rewrite

+ [ ] (#4270) To make it transactional (failures should revert back to where we started).
+ [ ] (#2141) To offer a `doom rollback` command.
+ [ ] (#3490) Make `doom sync` smarter about `:recipe` changes and stale bytecode (so you don't need to do that `doom sync -u` and `doom build` dance).
+ [ ] Improve the doctor API and checks, so we get more useful checks _and_ the warnings/errors they emit are less cryptic.
  + Check for misspelled modules and flags (#2048)
  + Warn users when they use inadvertently use package.el #4157
  + Support for a private doctor.el in your DOOMDIR (#4190)
  + Perform more sanity checks on your private config (#2959)
+ [ ] To fix our unit tests and add integration tests, powered by nix and buttercup.
+ [ ] CI/CD, so bumping packages can be automated (and tested).
+ [ ] To handle straight.el's prompts better -- or prevent them entirely. Re-cloning packages is better UX than these confusing prompts.

This is not an exhaustive list. 

## Other bugs

+ [ ] To fix whatever weirdness Windows is doing in #3844 

-----

I'll keep this post updated until the rewrite is done. There is no ETA on this.

**Comment by danilevy1212** [comment]
Hi! Anyway we can help you with this rewrite or features of this rewrite? Thanks for the awesome work.

**Comment by the-cobalt** [comment]
> Add a new `doom package ...` family of commands for per-package management

I think it might be better to integrate this into existing commands Using your example, instead of `doom package build x`, I think `doom build x` might be cleaner.

This is just a micro-aggression, but:
> they use inadvertently use package.el
I'm pretty sure that's a typo

Also, I think it would be nice to put this in like a "cli" branch, considering how this could be a breaking change, but people might want to keep track of/try it on their own.

**Comment by innerout** [comment]
If possible, I would suggest adding in the `doom upgrade` command a message informing the user that init.el has been updated with new options. This would be useful when a new module is added or when a new flag is added in a module.

**Comment by hlissner** [comment]
> If possible, I would suggest adding in the doom upgrade command a message informing the user that init.el has been updated with new options. This would be useful when a new module is added or when a new flag is added in a module.

@innerout I do have plans to address this:

1. A changelog to list module changes on our (as of yet unpublished) Discourse,
2. A doctor check that will complain about missing, renamed, or removed modules and flags.
3. A `doom whatsup` command that will summarize changes between generations (each time you run `doom upgrade`), including modules and packages.

1 and 2 are almost done, but 3 I haven't started on.

**Comment by hlissner** [comment]
> I think it might be better to integrate this into existing commands. Using your example, instead of doom package build x, I think doom build x might be cleaner.

@the-cobalt I plan to improve the user story for `doom sync`; make it smarter about outdated byte-code. Perhaps have something like a `--thorough` switch to replace `doom build`, but I consider it a bug that users have had to depend on `doom build` so much.

Not to mention, `build` would be only one of `doom package`'s prospective sub-commands. There'll be commands for resetting packages, byte-compiling, testing, snapshotting, bumping, and listing them -- among others. Because these are maintenance commands, I don't think they warrant a top-level command.

> I'm pretty sure that's a typo

Good catch! Fixed.

> Also, I think it would be nice to put this in like a "cli" branch, considering how this could be a breaking change, but people might want to keep track of/try it on their own.

I'm not certain this will happen, because it's a lot of work to support folks that decide to track it -- especially because Doom lacks adequate contributor documentation (something I plan to focus on after the rewrite). I'll let you know if that changes.

**Comment by hlissner** [comment]
> Any way we can help you with this rewrite or contribute to its features?

@danilevy1212 Thank you! Unfortunately there is little code work here to share right now. Another reason for this rewrite was to resolve Doom's technical debt and make onboarding people easier. It's difficult to coordinate any development effort when we have no CI, tests, or contributor documentation to shed light on our black box. Especially so when I am everyone's central resource for information and support.

That's why I have a Discourse coming up soon. I hope it will lift some of that weight off my shoulders -- Discord has proven a lousy archive for problems and solutions, the larger Doom grows. Now that I'm moving my development roadmap and progress reports there, I hope Doom's development will be more transparent (and so, easier to contribute to).

In the meantime, I do need help with:

+ Triage. Our issue tracker gets 1-6 new issues a day. 2 in 5 are non-issues (personal configuration or upstream problems). 1 in 6 are upstream or duplicates. I need help filtering those out. Otherwise, I need help prodding folks to do more testing, like:
  + Checking if their issue is reproducible [in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).
  + Making sure they've tried the usual `doom sync && doom build`.
  + Producing backtraces from error messages.
  + Reminding them to include their `M-x doom/info` when they have ignored the issue template.
+ There are a number of modules that still need documentation: https://github.com/hlissner/doom-emacs/issues/1166
+ [If you know your way around nix, adding a `shell.nix` to your favorite module(s) would be a big help](https://github.com/hlissner/doom-emacs/issues/2552). These will be the backbone of future CI. Plus, a minimum viable environment will help me debug issues for modules I don't use.

If those seem intimidating, it is also a great help stopping by [our Discord](https://discord.gg/qvGgnVx) or (when its up) [our Discourse](https://doomemacs.discourse.group) -- helping folks out or adding to the cheer.

**Comment by the-cobalt** [comment]
> commands for resetting packages, byte-compiling, testing, snapshotting, bumping, and listing them

Ok, for *all* of that, I think it *would* be better for all second level command, unless you wanted to go full "I'm an apt clone!" style, but that's out of the scope here.

> Good catch! Fixed.

Probably 76% of all of my PRs are just typo/grammar fixes. :wink: 

> I'm not certain this will happen, because it's a lot of work to support folks that decide to track it -- *especially because Doom lacks adequate contributor documentation* (something I plan to focus on after the rewrite). I'll let you know if that changes.

Yeah, probably working on that first *before* any kind of branching is a good idea.

**Comment by danilevy1212** [comment]
> > Any way we can help you with this rewrite or contribute to its features?
> 
> @danilevy1212 Thank you! Unfortunately there is little code work here to share right now. Another reason for this rewrite was to resolve Doom's technical debt and make onboarding people easier. It's difficult to coordinate any development effort when we have no CI, tests, or contributor documentation to shed light on our black box. Especially so when I am everyone's central resource for information and support.
> 
> That's why I have a Discourse coming up soon. I hope it will lift some of that weight off my shoulders -- Discord has proven a lousy archive for problems and solutions, the larger Doom grows. Now that I'm moving my development roadmap and progress reports there, I hope Doom's development will be more transparent (and so, easier to contribute to).
> 

Yeah, a man can only do so much although you constantly defy what that expression means :laughing:. Doom is a great project, it's good to focus now on better organization to be able to delegate tasks before it becomes a giant `spacemacs`.

> In the meantime, I do need help with:
> 
>     * Triage. Our issue tracker gets 1-6 new issues a day. 2 in 5 are non-issues (personal configuration or upstream problems). 1 in 6 are upstream or duplicates. I need help filtering those out. Otherwise, I need help prodding folks to do more testing, like:
> 
>       * Checking if their issue is reproducible [in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).
>       * Making sure they've tried the usual `doom sync && doom build`.
>       * Producing backtraces from error messages.
>       * Reminding them to include their `M-x doom/info` when they have ignored the issue template.

I've been popping into the discord a lot lately but not so much keeping an eye on issues. I'll see if can help out here too.

> 
>     * There are a number of modules that still need documentation: #1166
> 

Coincidentally, I am going through the modules one at the time configuring them to my liking, so I'll see if I can contribute to the documentation of those that had incomplete/missing READMEs. :+1: 

>     * [If you know your way around nix, adding a `shell.nix` to your favorite module(s) would be a big help](https://github.com/hlissner/doom-emacs/issues/2552). These will be the backbone of future CI. Plus, a minimum viable environment will help me debug issues for modules I don't use.
> 

Good thing I am looking into Nix at the moment, although it will be a while until I can help in this regard, total noob. :/

> 
> If those seem intimidating, it is also a great help stopping by [our Discord](https://discord.gg/qvGgnVx) or (when its up) [our Discourse](https://doomemacs.discourse.group) -- helping folks out or adding to the cheer.

Awesome, I will keep track of when discourse is up. Keep up the good work :smile:

**Comment by skrat** [comment]
Please only use one process by default when sync/build. Rendering the system unresponsive by default is a bad choice. Ie. `(setq native-comp-async-jobs-number 1)`

**Comment by danilevy1212** [comment]
Won't that make the compilation take much longer? @skrat

**Comment by skrat** [comment]
@danilevy1212 yes it will, decidedly. Right now it is so aggressive that it is the only thing on my system that can effectively disable it for extended period of time. And if you want to make it pronto and grab a lunch meanwhile, you can use a flag/setting.

**Comment by jerbaroo** [comment]
> Add -f switch to doom sync to suppress prompts.

A user could just run `yes | doom sync` to do this?

**Comment by acristoffers** [comment]
>       x There was an unexpected error
>        Message: File error
>        Error: (file-error "Creating pipe" "Too many open files")

I'm having this problem when running `doom build`. It always fails at pdf-tools, but if I remove the pdf module from the configuration it then fails a bit later, so the problem is not exactly with a package/module.

It does not happen when running `doom upgrade` though.

**Comment by danilevy1212** [comment]
This happens to me on a fresh install everytime. I do have a a lots of packages and modules. Still, this seems like emacs has open file handles that it does not close.

**Comment by acristoffers** [comment]
Repeating the install command did not make a difference for me, it still gives the error at the same spot.

**Comment by innerout** [comment]
Have you tried raising the upper limit for open files in your OS?

**Comment by acristoffers** [comment]
Actually, yes. I ran `launchctl limit maxfiles 200000` and then it worked. However, what are the downsides of doing that? There's a limit for a reason, I guess?

**Comment by innerout** [comment]
This is from the top of my head, and I hope I do not forget something crucial. By raising the limit, your kernel could allocate more file descriptors for files in your system if a malicious application appears. These file descriptors could result in hogging resources from processes that may need them. However, I do not believe this could happen. Also, the file descriptor limit may be a legacy configuration that has been set as a good default.

**Comment by acristoffers** [comment]
For anyone finding this thread and still having issues, today I had problems again and running the `launchctl` command did not help. Instead, running `ulimit -n 2048` worked. It seems that `ulimit` is set by terminal session, so you can mess with it and then just close that session without polluting your environment. You may also try a combination of those, I'm not sure exactly what the steps to fix it are. To test it properly I would have to reboot to get a clean environment to test, but right now I cannot. I'll try to test it correctly once I can reboot.

**Comment by hlissner** [comment]
> Please only use one process by default when sync/build. Rendering the system unresponsive by default is a bad choice. Ie. (setq native-comp-async-jobs-number 1) and also make sure the underlying build system/compiler also uses just one core.

@skrat As of https://github.com/doomemacs/doomemacs/commit/498d88ba9bc5941ad95ff006a74b2021e294447f, `doom {build,sync,upgrade}` all take a `-j/--jobs NUM` option to specify how many threads to use, but the default will remain at "all cores".

> (file-error "Creating pipe" "Too many open files")

This issue has been summarized nicely [on our Discourse](https://discourse.doomemacs.org/t/fix-for-doom-build-too-many-open-files-on-native-comp/2650). Please move any discussion about it over there.

-----

Anyhow, there's been some movement on this issue. 6c0b7e1 paves the way for rest of the CLI rewrite, which I will be focusing on starting next week. For the month thereafter I will be sprinting Doom development. I'll post again once there's more progress.

**Comment by mangkoran** [comment]
I just done `doom upgrade` to f913ff07b3a63d57ca0de48037e9098f0a598791. When I tried to do `doom purge`, it will do `doom build` instead. 

```
❯ doom purge
> (Re)building all packages...
  > Building straight...
  > Building use-package...
  > Building use-package > Building bind-key...
  > Building use-package...
  > Building auto-minor-mode...
```

**Comment by harabat** [comment]
> I just done `doom upgrade` to [f913ff0](https://github.com/doomemacs/doomemacs/commit/f913ff07b3a63d57ca0de48037e9098f0a598791). When I tried to do `doom purge`, it will do `doom build` instead.

Observing something similar since upgrading 2 days ago:
- `doom purge` == `doom build`
- `doom sync` does not take into account my literate config file (I tried [upgrading manually](https://github.com/doomemacs/doomemacs/issues/6472#issuecomment-1159707428))

**Comment by hlissner** [comment]
@mangkoran @harabat Thanks for letting me know! This was fixed in d226946f59ec1174a58867105a392c687e6b3334.

**Comment by mangkoran** [comment]
@hlissner I am on d6d1e600c0b22ce323558002eccdaac6edbcf2b2 but `doom purge` still doing `doom build` instead.

**Comment by hlissner** [comment]
@mangkoran That should be fixed in 834ff3ea852ce5792d2427e1a697190db982f676.

**Comment by acristoffers** [comment]
The `-f` option was removed, but there are still errors mentioning it:

```
Error: Refusing to upgrade because "~/.emacs.d/" has been modified.

Either stash/undo your changes or run 'doom upgrade -f' to discard local changes.

 M modules/os/macos/autoload.el

Aborting...
```

But then running `doom upgrade -f`, as suggested, we get:

```
Error: unknown option -f

Usage: doom upgrade [-p|--packages] [-j|--jobs NUM]

See 'doom h[elp] upgrade' or 'doom upgrade {-?,--help}' for documentation.
```
